// <auto-generated />
namespace BOSS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lastmenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastmenu));
        
        string IMigrationMetadata.Id
        {
            get { return "202005261703039_last-menu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
